#!/bin/bash

# Turn off
USERNAME=dmelchor
HOST=dmelchorpi.local
ssh $USERNAME@$HOST "cd ~/finances && docker compose down"

if [[ "$*" == *--build* ]]; then
    docker compose build 
    docker push dmelchor/finances-api:latest
    docker push dmelchor/finances-frontend:latest
fi

# ---- Deploy ----

# Make directory
ssh $USERNAME@$HOST "mkdir -p ~/finances"

# Copy necessary files
scp docker-compose.yaml $USERNAME@$HOST:~/finances
scp .env $USERNAME@$HOST:~/finances
scp -r db $USERNAME@$HOST:~/finances


if [[ "$*" == *--erase* ]]; then
    # Remove docker volume
    ssh $USERNAME@$HOST "cd ~/finances && docker volume rm finances_postgres_data"
fi

# Pull and run docker
ssh $USERNAME@$HOST "cd ~/finances && docker compose pull"
ssh $USERNAME@$HOST "cd ~/finances && docker compose up -d"

if [[ "$*" == *--erase* ]]; then
    # Register user
    read -p "Username: " USER
    read -p "Password: " -s PASSWORD
    echo
    read -p "Email: " EMAIL
    ssh $USERNAME@$HOST "docker exec api /cli create-user --username $USER --password $PASSWORD --email $EMAIL"
fi


echo "Deployed successfully!"
