services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: dmelchor/finances-db:latest
    container_name: db
    env_file:
      - stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finances
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: dmelchor/finances-api:latest
    container_name: api
    env_file:
      - stack.env
    depends_on:
      - db
    networks:
      - finances
      - traefik
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://api:8000
        - AUTH_URL=http://auth-api:8000
    image: dmelchor/finances-frontend:latest
    container_name: frontend
    env_file:
      - stack.env
    depends_on:
    - api
    networks:
      - finances
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.finance.rule=Host(`finance.dmelchor.lan`)
      - traefik.http.routers.finance.entrypoints=web
      - traefik.port=3000
      - "traefik.http.routers.finance.middlewares=auth@file"

volumes:
  postgres_data:

networks:
  finances:
  traefik:
    external: true
