services:
  dev-db:
    image: postgres:16-alpine
    env_file:
      - stack.dev.env
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - finances-network

  dev-api:
    image: golang:1.22.6-alpine
    env_file:
      - stack.dev.env
    volumes:
      - ./api:/app
    depends_on:
      - dev-db
    networks:
      - finances-network
    command: go run cmd/service/main.go
    working_dir: /app

  dev-frontend:
    image: node:22-alpine
    command: npm run dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
    - dev-api
    ports:
      - "3000:3000"
    networks:
      - finances-network
    environment:
      - API_URL=http://dev-api:8000

volumes:
  dev_postgres_data:

networks:
  finances-network:
